name: Deploy NextJs to AWS S3

on:
    push:
      branches:
        [ master ]
      paths:
        - 'web-app/**'
    
    workflow_dispatch:

env:

jobs:
    deploy:
        runs-on: ubuntu-latest

        steps:
          # Step1: Checkout the repository code
          - uses: actions/checkout@v4
            with:
                submodules: true
                lfs: false
         # step 2: Setup Node.js environment
          - name: Setup Nodejs version
            uses: actions/setup-node@v4
            with:
                node-version: "22.x"
                cache: 'npm'
                cache-dependency-path: 'web-app/package-lock.json'
        # step 3: Install dependencies
          - name: Install dependencies
            working-directory: ./web-app
            run: npm install
        # step 4: Build Next.js app
          - name: Build Next.js app
            working-directory: ./web-app
            run: npm run build
        # step 5: Configure AWS Credentials
          - name: Configure AWS Credentials
            uses: aws-actions/configure-aws-credentials@v1
            with: 
                aws-access-key-id: ${{secrets.AWS_ACCESS_KEY}}
                aws-secret-access-key: ${{secrets.AWS_SECRET_ACCESS_KEY}}
                aws-region: ${{secrets.AWS_REGION}}
        # step 6: Deploy to AWS S3
          - name: Deploy to AWS S3
            run: aws s3 sync build s3://${{secrets.AWS_BUCKET}} --delete
        

